server:
  port: 8091

spring:
  servlet:    multipart:
      max-request-size: 10MB      max-file-size: 10MB
  profiles:
    active: dev
  datasource:
    password: mysecretpassword
    url: jdbc:mysql://localhost:3306/agrisud_mediatheque
    username: root

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3800/auth/realms/agrisud

cloud:
  server:
    name: http://localhost:3900
    password: cloudagrisudcrud
    username: cloudagrisudcrud

keycloak:
  resource: agrisud-mediatheque-api
  allowed-origin: http://localhost:3001


