CREATE TABLE STATISTIC_MEDIA (
    STATISTIC_MEDIA_ID bigint(20) key NOT NULL AUTO_INCREMENT,
    CATEGORY_ID bigint(20),
    TYPE_CATEGORY varchar(255),
    MEDIA_ID bigint(20),
    ACTION varchar(100),
    DATE_ACTION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_id_satistic FOREIGN KEY (category_id)
        REFERENCES CATEGORY (category_id) ON DELETE CASCADE
);