CREATE TABLE THEMATIC_FOLDER (
    THEMATIC_FOLDER_ID bigint(20) key NOT NULL AUTO_INCREMENT,
    CATEGORY_ID bigint(20),
    TITLE_FRANCAIS varchar(150),
    TITLE_ANGLAIS varchar(150),
    PATH_FOLDER text,
    PATH_IMAGE text,
    URL_IMAGE text,
    PARENT_ID bigint(20)
);