CREATE TABLE THEMATIC_FOLDER_MEDIA (
    THEMATIC_FOLDER_MEDIA_ID bigint(20) key NOT NULL AUTO_INCREMENT,
    CATEGORY_ID bigint(20),
    TYPE_CATEGORY varchar(255),
    PARENT_ID bigint(20),
    MEDIA_ID bigint(20)
);